name: Run isort
on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run isort
        uses: isort/isort-action@v1
        with:
          requirements-files: "requirements.txt requirements-test.txt"
